name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    name: Go 1.17 on Linux

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Build and Test
      run: |
        go test

  build-windows:
    runs-on: windows-latest

    name: Go 1.17 on Windows

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Build and Test
      run: |
        go test
